### ISSUE TITLE
Not Support import file

### ISSUE THREAD

**Issue by Q-Peppa** [Q-Peppa/react-css-modules-all#7]
## Not Completion class name it in @import file 

`styles.scss`
```scss
@import "common";
.action-buttons {
  color: #4285f4;
}
```
--- 
`common.scss`

```scss
.test {
 color: #4285f4;
}
```

--- 

```jsx
import styles from "./styles.scss";
styles.  <---- // there is not `test`
```

### Relevant log output or stack trace

```shell

```

### Steps to reproduce

⬆️

### Gradle IntelliJ Plugin version

2.5.0

### Gradle version

8.13

### Operating System

Windows
